### ISSUE TITLE
Install fails on wp-multisite

### ISSUE THREAD

**Issue by jbonlinea** [agileware/wp-civicrm-ux#1]
Hi there, 

Following a recent conversation [here](https://github.com/christianwach/civicrm-acf-integration/issues/2) I tried to install this plug-in but if fails, wp returns that no valid extension could be found ? 

No sure if I missed something in the documentation but I haven't seen any specific installation process ? 

the site is running wp 5.4.2 on php 7.3

Hope you may help

EDIT 

The install went trhough on a wordpress site, but it failed on a wp multi site install?

Regards

**Comment by agileware-justin** [comment]
@jbonlinea thanks for reporting, we have not tested this at all on multi-site. There's likely some assumptions in the code which are not correct in this configuration.

If you have time to review the and advise or submit a PR where the problem lies, that would be appreciated.

**Comment by jbonlinea** [comment]
Hi again, actually it might not be multi-site related, as for some unknown reason yet i can't automatically install any plug-in anymore ?! (I don't think the install failure of your plug-in brock the whole plug-in install)

I'll have to digg a little deeper and come ack to you, but don't expect deep support, I'm more a java script guy and I handle coding boradly speaking, but i'm not really wordpress codex aware :)
