### ISSUE TITLE
Notice when shortcode could not retrive data

### ISSUE THREAD

**Issue by jbonlinea** [agileware/wp-civicrm-ux#10]
Hi there

again a very minor feedback but that might be good to know.

I use the plugin to display wp-users<=>civi-contact membership statut mostly, and it work's great ! thank's for that.
Obviouly not all users are "members".
When a user who is not a member browse a page where wp-civicrm-ux shortcode are present, php retunr a notice ; the folowing in my case, but it is related to the data I'm displaying.

```
Notice: Undefined variable: renewal_date_format in /home/html/wp-content/plugins/wp-civicrm-ux/includes/utils/class-civicrm-ux-membership-utils.php on line 293

Notice: Undefined variable: renewal_date_format in /home/html/wp-content/plugins/wp-civicrm-ux/includes/utils/class-civicrm-ux-membership-utils.php on line 293
```

edit : still using wp-civicrm-ux 1.1.2 as I can't activate the latest one

**Comment by agileware-justin** [comment]
Thanks for reporting, this has been fixed.

**Comment by jbonlinea** [comment]
:+1: 
:rocket:
