### ISSUE TITLE
WP-CiviCRM-UX and JS/JQuery loading

### ISSUE THREAD

**Issue by jbonlinea** [agileware/wp-civicrm-ux#11]
Hi 

I've bumped into something I have to share here, at least before bringing it elsewhere because it is obviously broader.

Long story short,
- CiviCRM paiement option are not displayed properly, the pages (contribution, event registration, etc.) returns a lot of JS errors on a site running Divi theme (that I would not advocat fore, but it is how it is in this case), and of course the whole form is not usable.
- but if wp-civicrm-ux is enable on the site, everything is back on !!! :D

I've been doing some few test, disabling all the plug-in, and back to twentyyXXX.
whatever the mix is, if the theme is Divi (or a divi child theme), the civicrm pages with paiement are messed up but if wp-civicrm-ux is active.

I do assume it is related to js loading "timing", more specifically blocking loading page dome element untill jquery is loaded ? 

I'm not sure there are many site that use CiviCRM and Divi, but this might be interesting to broaden the issue of loading jquery in a theme compatibility perspective.

EDIT : I forgot to mention that using any of the wp jquery updater plugin do not solve the situaton when wp-civicrm-ux is not active, and event re-break the form when wp-civicrm-ux is active

Regards

edit : still using wp-civicrm-ux 1.1.2 as I can't activate the latest one

**Comment by agileware-justin** [comment]
@jbonlinea My first guess here is that CiviCRM short-codes will not work on any page using the Divi Editor. You can use the Divi theme on the website, it's just the specific pages where the CiviCRM short-codes are included where the Divi Editor should not be enabled.

So you can confirm if this is the case by disabling the Divi Editor on the page, saving and then viewing the page again. If there's no JS errors then that's the problem.

I have a feeling we might have solved the Divi / CiviCRM incompatibility at some stage in the past. I'll post a follow-up here if that's the case - silence will mean no, still an issue.

**Comment by jbonlinea** [comment]
Actaully the page is built with gutemberg, not divi, but now divi is a theme buildel as well and thus the header and footer are build with divi, but not what belongs to `post_content`

I'll do some more testing and get back to you, or if you can direct me where should I report Divi issue I'll interact there directly :)

**Comment by agileware-justin** [comment]
We've not had any issues with this at all. So would be good to get some details.

**Comment by agileware-fj** [comment]
Closing this issue since no more details were added
