### ISSUE TITLE
Can't enable latest update

### ISSUE THREAD

**Issue by jbonlinea** [agileware/wp-civicrm-ux#12]
Hi there, 

I've  `git pull` the repo succesfully but can't activate the plugin, getting this error : 

`Parse error: syntax error, unexpected '=>' (T_DOUBLE_ARROW), expecting ')' in /home/html/wp-content/plugins/wp-civicrm-ux/shortcodes/civicrm/api4-get.php on line 43`

Regards

Otherwise I used the 1.1.2 and it work's

my actual set-up is
wp 5.8.1
civi 5.41
and various civi related plugins (ACU, profile sync, member sync, etc.)

**Comment by christianwach** [comment]
@jbonlinea That's [PHP 7.4 syntax](https://www.php.net/manual/en/functions.arrow.php). The plugin should ideally [declare the minimum required version of PHP in its header](https://developer.wordpress.org/plugins/plugin-basics/header-requirements/) if it's unusual.

**Comment by agileware-justin** [comment]
Thanks for reporting @jbonlinea and also for the advise @christianwach 

@jbonlinea you will need to update to PHP 7.4 with the latest version. Hope that's possible. I've added the requirements to the plugin in 1.8.2

**Comment by jbonlinea** [comment]
Hi,

Thank's for the feedback, 

Yes I can switch to 7.4, but I've been fooled by the [Civicrm install guide](https://docs.civicrm.org/installation/en/latest/general/requirements/)  php version table, not paying attention that the Civ ESR version only was not compatible with 7.4
