### ISSUE TITLE
Commit 516881729fd26849146710d770677ee608c9288b prevented some shortcodes from loading correctly

### ISSUE THREAD

**Issue by wcha-peter** [agileware/wp-civicrm-ux#20]
The changes to line 296 seem to lead to the `Civicrm_Ux_Loader->run()` not being run on initialization, so some (all?) short codes do not get registered, such as the `ux_cv_api4_get ` shortcode.

When the line is adjusted from `add_action('init', [$this->loader, 'run']);` to `add_action('init', $this->loader->run());` or `$this->loader->run()`, the changes to `Civicrm_Ux_Loader` causes the following error `PHP Fatal error:  Uncaught Error: Call to a member function initialize() on null in wp-content/plugins/civicrm/civicrm.php:952` when `magic-tags/activity.php` tries to initialize.

Best wishes,
Peter

**Comment by agileware-justin** [comment]
@wcha-peter thanks for the issue, yes we discussed and are aware of this problem. I've pulled that release and we'll fix that problem.

**Comment by agileware-justin** [comment]
Issue was fixed in 1.9.4, https://github.com/agileware/wp-civicrm-ux/releases/tag/1.9.4

Recommended release is 1.11.0, https://github.com/agileware/wp-civicrm-ux/releases/tag/1.11.0
