### ISSUE TITLE
Thermometer stalled

### ISSUE THREAD

**Issue by CoreyBurger** [agileware/wp-civicrm-ux#3]
The thermometer for a campaign has stalled at a value, despite several more completed transactions.

CiviCRM 5.29.1 on Wordress 5.5

**Comment by CoreyBurger** [comment]
I did some more digging and it looks like it stalled right before a contribution that created a new contact, so it is possible that there is some sort of issue with that.

Further, the following work correctly:
[ux_campaign_honour_listing id=8 display-amount=true]
or 
[ux_campaign_honour_listing id=8 display-amount=false]
- both of these show all 23 contributions

However, both 
[ux_campaign_total_raised id=8]
and
[ux_campaign_number_contributions id=8]
both don't show the correct value or correct number of contributions.

**Comment by agileware-justin** [comment]
@CoreyBurger sorry, no idea how to solve this one - would require debugging on your site to find out exactly what is going on here.

**Comment by CoreyBurger** [comment]
Happy to debug, but not certain how to start

**Comment by agileware-justin** [comment]
@CoreyBurger Can you set up a sandbox WP + CiviCRM site with just test data, that can replicate the problem? If so, then archive and provide a download link so we can check it out.

**Comment by CoreyBurger** [comment]
Will do. Might be a week or so to get it done.

**Comment by agileware-justin** [comment]
@CoreyBurger no rush

**Comment by agileware-justin** [comment]
Issue queue clean-up, closing old issue
